### ISSUE TITLE
感觉这个分词的simhash 对词性相近的毫无作用

### ISSUE THREAD

**Issue by penhauer-xiao** [gensmusic/simhash#3]
如下面这段文字，肯定说的是一个意思，但比较出来， 值是29

```装饰其实也是十分讲究时尚的，每个期间都有不一样的装饰办法，今日小编给我们盘点4种丑爆了的装饰办法，看看这些过期的装饰，你家还在用吗？最少如今看起来，是十分老土的一种装饰办法了。```

```装修其实也是非常讲求时髦的，每个时期都有不同的装修方法，今天小编给大家盘点4种丑爆了的装修方法，看看这些过时的装修，你家还在用吗？起码现在看起来，是非常老土的一种装修方法了。```

```
simhash1: 4fe23661ff4ab6d3 5756223068255729363 
simhash2:bfbf33b1fe48c98c: 13816819021364382092
diff: 29
```

**Comment by penhauer-xiao** [comment]
分词对比， 只是替换了相似词就比较不出来了，差区好大：

```"装饰", "其实", "十分", "讲究", "时尚", "每个", "期间", "装饰", "办法", "今日", "小编", "盘点", "种丑", "装饰", "办法", "看看", "过期", "装饰", "你家", "最少", "如今", "看起来", "十分", "老土", "一种", "装饰", "办法"```

```"装修", "其实", "非常", "讲求", "时髦", "每个", "时期", "不同", "装修", "方法", "今天", "小编", "盘点", "种丑", "装修", "方法", "看看", "过时", "装修", "你家", "起码", "现在", "看起来", "非常", "老土", "一种", "装修", "方法"```

**Comment by penhauer-xiao** [comment]
感觉要要有同义词字典， 同一种同义词， 近义词算为一个短hash,这样的话，才准确
```
List<Word> words = WordSegmenter.segWithStopWords("楚离陌千方百计为无情找回记忆");
System.out.println(words);
结果如下：
[楚离陌, 千方百计, 为, 无情, 找回, 记忆]
做同义标注：
SynonymTagging.process(words);
System.out.println(words);
结果如下：
[楚离陌, 千方百计[久有存心, 化尽心血, 想方设法, 费尽心机], 为, 无情, 找回, 记忆[影象]]
如果启用间接同义词：
SynonymTagging.process(words, false);
System.out.println(words);
结果如下：
[楚离陌, 千方百计[久有存心, 化尽心血, 想方设法, 费尽心机], 为, 无情, 找回, 记忆[影像, 影象]]
```

**Comment by gensmusic** [comment]
我这里没有使用同义词．可以研究一下

**Comment by penhauer-xiao** [comment]
@gensmusic 不是是之前有什么项目驱动研究这个呢？

**Comment by gensmusic** [comment]
@penhauer-xiao 是的，我有一个项目是做文本排重的．实现了simhash和 minhash等等算法．这里的仅仅算是一个小demo吧.真实产品不敢拿出来,毕竟是公司的.

**Comment by penhauer-xiao** [comment]
@gensmusic 看来你们排重不严格呵, 同义词还是挺常见的

**Comment by gensmusic** [comment]
@penhauer-xiao   我们还有别的排重算法的，除非他把超过50%以上的词全部替换成同义词，要不然是没啥影响的

**Comment by penhauer-xiao** [comment]
@gensmusic 其它排重算法? 也是基于hash的，还是基于关键字的呢，好像业界目前就是google simhash比较有名

**Comment by gensmusic** [comment]
@penhauer-xiao simhash只是一种工程实现特别简单的方案而已。推荐你去看 数据挖掘那本书。
